trigger: none

parameters:
- name: targetEnvironment
  type: string
  default: dev
  values: 
  - dev
  - uat
  - prod
- name: executionMode
  type: string
  default: plan
  values:
  - plan
  - apply
  - destroy
# azure-pipelines.yml
stages:
- template: tf-template.yml
  parameters:
    targetEnvironment: ${{ parameters.targetEnvironment }} # target environment for deployment (dev, uat, prod)
    executionMode: ${{ parameters.executionMode }} # plan, apply, destroy
    serviceConnectionName : 'ado-contosso-subsc' # service connection name in Azure DevOps for connecting to Azure subscription
    environmentName: 'smilesweb-dev' # environment name in Azure DevOps for deployment and approval gates
    variableGroupName: 'test-mathu-var-grp' # variable group name in Azure DevOps for storing secrets and variables

# - ${{ if eq(parameters.targetEnvironment, 'prod') }}:
#    - template: tf-stage.yml
#      parameters:
#        targetEnvironment: ${{ parameters.targetEnvironment }}
#        executionMode: ${{ parameters.executionMode }}
#        serviceConnectionName : 'svc-ado-deem_devops'
#        environmentName: 'Deem-Production'
#        variableGroupName: 'deem-prod-variables'
